#!/bin/sh
set -e

PREREQS=""
case $1 in
    prereqs) echo "${PREREQS}"; exit 0;;
esac

. /usr/share/initramfs-tools/hook-functions

##
for pname in sfdisk growpart udevadm; do
    fpath=$(which "$pname") && copy_exec "$fpath" ||
        { echo "ERROR: no '$pname' in path" 1>&2; exit 1; }
done

# vi: ts=4 noexpandtab
