#!/bin/sh
#  Copyright, 2014 Scott Moser <smoser@ubuntu.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see
#    <http://www.gnu.org/licenses/>.

prereqs() {
	[ -e /scripts/init-bottom/overlayroot ] && echo "overlayroot";
}

[ "$1" != "prereqs" ] || { prereqs; exit 0; }

. /scripts/functions

set -f
PATH=/usr/sbin:/usr/bin:/sbin:/bin

cmdline=""
myopts=""
if [ -f /proc/cmdline ]; then
	read cmdline < /proc/cmdline
	for tok in cmdline; do
		[ "${tok#copymods=}" != "$tok" ] || continue
		myopts="${tok#copymods=}"
	done
fi
myver=$(uname -r)

if [ ! -d "/lib/modules/$myver" ]; then
	log_warn_msg "Something odd, no /lib/modules/$myver."
	exit 0
fi

[ -d "$rootmnt/lib/modules" ] ||
	{ log_warn_msg "No /lib/modules in target. cannot help."; exit 0; }

if [ -d "$rootmnt/lib/modules/$myver" ]; then
	if [ "${myopts#*force}" = "$myopts" ]; then
		log_warn_msg "Modules existed for $myver in target. use copymods=force."
		exit 0
	else
		log_warn_msg "copying over existing modules! due to copymods=force"
	fi
fi

mount -t tmpfs copymods "$rootmnt/lib/modules" ||
	{ log_failure_msg "failed mount of tmpfs"; exit 0; }

mv "/lib/modules/$myver" "$rootmnt/lib/modules" ||
	{ log_failure_msg "failed to copy modules to target root"; exit 0; }

# vi: ts=4 noexpandtab
