#!/bin/sh

PREREQ=""
case $1 in
    prereqs) echo "${PREREQS}"; exit 0;;
esac

VERBOSITY="1"

debug() {
	local v=$1
	shift
	[ $v -lt $VERBOSITY ] && return 0
	echo "::" "$@"
}

mount_tar() {
	local target="$1" urls="$2" url=""
	[ -d "$target" ] || mkdir -p "$target" || return
	mount -t tmpfs root_url "$target" || return

	local oifs="$IFS"
	IFS=","; set -- $urls; IFS="$oifs"

	local zopt=""
	for url in "$@"; do
        case "$url" in
           *.tar.gz|*.tgz) zopt="z";;
           *.tar.xz|*.txz) zopt="J";;
        esac
		debug 1 "# [$zopt] $url"
		wget "$url" -O - | tar -C "$target" -xp${zopt}f -
	done
	[ -x "$target/sbin" ]
}

. /scripts/functions

case "$ROOT" in
	http://*) :;;
	*) exit 0
esac
configure_networking || exit

debug 1 "root=$ROOT"
mount_tar "${rootmnt}.tmp" "$ROOT" || exit

{
	echo 'ROOTFSTYPE="root_url"'
	echo 'ROOTFLAGS="${ROOTFLAGS:+${ROOT_FLAGS} }-o move"'
	echo "ROOT=\"$rootmnt.tmp\""
} > /conf/param.conf

# vi: ts=4 noexpandtab
